version: '3'
services: 
  hadoop-master:
    build: ../hadoop-base/
    container_name: hadoop-master
    restart: always
    ports:
      - 50070:50070
      - 8020:8020
    command: /usr/sbin/sshd -D && /opt/hadoop/sbin/start-all.sh

  hadoop-slave1:
    build: ../hadoop-base/
    container_name: hadoop-slave1
    restart: always

  hadoop-slave2:
    build: ../hadoop-base/
    container_name: hadoop-slave2
    restart: always

  hadoop-slave3:
    build: ../hadoop-base/
    container_name: hadoop-slave3
    restart: always

