version: '3'

services: 
  spark-master:
    build: ../spark-base/
    container_name: spark-master
    ports:
      - 4000:4000
      - 8080:8080
      - 7077:7077
    depends_on: 
      - hadoop-master
      - spark-slave1
      - spark-slave2
    command: /usr/local/bin/entrypoint.sh

  spark-slave1:
    build: ../spark-base/
    container_name: spark-slave1

  spark-slave2:
    build: ../spark-base/
    container_name: spark-slave2


  hadoop-master:
    build: ../hadoop-base/
    container_name: hadoop-master
    ports:
      - 50070:50070
      - 8020:8020
    depends_on: 
      - hadoop-slave1
      - hadoop-slave2
      - hadoop-slave3
    command: /usr/local/bin/entrypoint.sh

  hadoop-slave1:
    build: ../hadoop-base/
    container_name: hadoop-slave1

  hadoop-slave2:
    build: ../hadoop-base/
    container_name: hadoop-slave2

  hadoop-slave3:
    build: ../hadoop-base/
    container_name: hadoop-slave3