version: '3'

services: 
  spark-master:
    build: ../spark-base/
    container_name: spark-master
    restart: always
    ports:
      - 4000:4000
      - 8080:8080

  spark-slave1:
    build: ../spark-base/
    container_name: spark-slave1
    restart: always

  spark-slave2:
    build: ../spark-base/
    container_name: spark-slave2
    restart: always
  
  hadoop-master:
    build: ../hadoop-base/
    container_name: hadoop-master
    restart: always
    ports:
      - 50070:50070
      - 8020:8020

  hadoop-slave1:
    build: ../hadoop-base/
    container_name: hadoop-slave1
    restart: always

  hadoop-slave2:
    build: ../hadoop-base/
    container_name: hadoop-slave2
    restart: always

  hadoop-slave3:
    build: ../hadoop-base/
    container_name: hadoop-slave3
    restart: always